$( function () {

	//Case Sliders
	$( "#numbDefSlide" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 100,
		from: 0,
		to: 100,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	//Denfendant Sliders
	$( "#yearBirthDefendant" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 1930,
		max: 2014,
		from: 1930,
		to: 2014,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	//Judge Sliders
	$( "#yearAppointJudge" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 1960,
		max: 2020,
		from: 1960,
		to: 2020,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	//Victim Sliders
	$( "#totalSlide" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 100,
		from: 0,
		to: 100,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#minorSlide" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 100,
		from: 0,
		to: 100,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#foreignerSlide" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 100,
		from: 0,
		to: 100,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#femaleSlide" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 100,
		from: 0,
		to: 100,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	//Arrest Details Sliders
	$( "#dateArrestAD" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 2000,
		max: 2020,
		from: 2000,
		to: 2020,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#bailAmountArrest" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 1000,
		max: 100000,
		from: 1000,
		to: 100000,
		type: 'integer',
		step: 1,
		prefix: "$",
		max_postfix: '+',
		grid: true
	} );
	//Charge Details Sliders
	$( "#chargeDate" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 2000,
		max: 2020,
		from: 2000,
		to: 2020,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#totalCharges" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 20,
		from: 0,
		to: 20,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#countsCharge" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#countsNolleProssed" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#pleaDismiss" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#pleaGuilty" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#trialGuilty" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#trialNotGuilty" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#sentenceCharge" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 300,
		from: 0,
		to: 300,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#probationCharge" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 300,
		from: 0,
		to: 300,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );

	//Sentencing Details Sliders
	$( "#totalNumFelonySentence" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10,
		from: 0,
		to: 10,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#dateTermSentenced" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 2000,
		max: 2020,
		from: 2000,
		to: 2020,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#totalMonthsSentenced" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 300,
		from: 0,
		to: 300,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
	$( "#amountRestitutionSent" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 10000000,
		from: 0,
		to: 10000000,
		type: 'integer',
		step: 1,
		prefix: "$",
		max_postfix: '+',
		grid: true
	} );
	$( "#monthsProbationSentence" ).ionRangeSlider( {
		hide_min_max: true,
		keyboard: true,
		min: 0,
		max: 50,
		from: 0,
		to: 50,
		type: 'integer',
		step: 1,
		prefix: "",
		max_postfix: '+',
		grid: true
	} );
} );